# Generated by Django 4.2.6 on 2023-10-13 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cliente", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=256, unique=True)),
                ("cantidad", models.IntegerField(default=0)),
                ("precio", models.FloatField(default=0.0)),
                ("descuento", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name": "Libro",
                "verbose_name_plural": "Libros",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Linea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField(default=0)),
                ("pvp", models.FloatField(default=0.0)),
                ("precio", models.FloatField(default=0.0)),
                ("importe_total", models.FloatField(default=0.0)),
                (
                    "libro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="facturacion.libro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea Factura/Pedido",
                "verbose_name_plural": "Líneas Factura/Pedido",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pedido", models.DateField(blank=True, null=True)),
                ("fecha_ingreso", models.DateField(blank=True, null=True)),
                ("precio_total_sin_iva", models.FloatField(default=0.0)),
                ("precio_total_iva", models.FloatField(default=0.0)),
                ("descuento", models.FloatField(default=0.0)),
                ("gastos_envio", models.FloatField(default=0.0)),
                (
                    "forma_cobro",
                    models.CharField(
                        choices=[("TAR", "Tarjeta"), ("TRA", "Transferencia")],
                        default="TAR",
                        max_length=3,
                    ),
                ),
                ("ingreso_banco", models.FloatField(default=0.0)),
                ("recargo_equivalencia", models.FloatField(default=0.0)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="cliente.cliente",
                    ),
                ),
                ("lineas", models.ManyToManyField(to="facturacion.linea")),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pedido", models.DateField(blank=True, null=True)),
                ("fecha_ingreso", models.DateField(blank=True, null=True)),
                ("precio_total_sin_iva", models.FloatField(default=0.0)),
                ("precio_total_iva", models.FloatField(default=0.0)),
                ("descuento", models.FloatField(default=0.0)),
                ("gastos_envio", models.FloatField(default=0.0)),
                (
                    "forma_cobro",
                    models.CharField(
                        choices=[("TAR", "Tarjeta"), ("TRA", "Transferencia")],
                        default="TAR",
                        max_length=3,
                    ),
                ),
                ("ingreso_banco", models.FloatField(default=0.0)),
                ("recargo_equivalencia", models.FloatField(default=0.0)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="cliente.cliente",
                    ),
                ),
                ("lineas", models.ManyToManyField(to="facturacion.linea")),
            ],
            options={
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
                "ordering": ["pk"],
            },
        ),
    ]
